### PR TITLE
Fix feature uninstall bug

### LINKED ISSUE #66: feature uninstallation fails due to incorrect "shared" argument
In the current implementation of `carbon-maven-plugins/carbon-feature-plugin/src/main/java/org/wso2/maven/p2/utils/P2ApplicationLaunchManager.java `, the `-shared` argument of the method `addArgumentsToUnInstallFeatures` does not points to the correct location of `p2`. This makes feature uninstallation fails.

### PR DESCRIPTION
**Pull request by kasunsiyambalapitiya**
Fixed `-shared` P2ApplicationLauncher argument in `addArgumentsToUnInstallFeatures` method so that it points to the new location of `p2`
Resolves  #66

### CODE REVIEW

**Comment by Niranjan-K** [comment]
@kasunsiyambalapitiya : PR title is too long. Shall we reduce it?

File: carbon-feature-plugin/src/main/java/org/wso2/maven/p2/utils/P2ApplicationLaunchManager.java [hunk 1]
```diff
@@ -111,8 +111,8 @@ public void addArgumentsToUnInstallFeatures(String uninstallIUs, String destinat
                 // the location of where the plug-ins and features will be stored. This value is only taken into account
                 // when a new profile is created. For an application where all the bundles are located into the
                 // plugins/ folder of the destination, set it to <destination>
-                // use a shared location for the install. The path defaults to ${user.home}/.p2
-                "-shared", Paths.get(destination + File.separator + "p2").toString(),
+                // to support shared installation in carbon
+                "-shared", Paths.get(destination + File.separator + "lib" + File.separator + "p2").toString(),
```
Comment (laki88) [inline carbon-feature-plugin/src/main/java/org/wso2/maven/p2/utils/P2ApplicationLaunchManager.java]: we don't need FileSeparator for paths.get()?

Comment (kasunsiyambalapitiya) [reply carbon-feature-plugin/src/main/java/org/wso2/maven/p2/utils/P2ApplicationLaunchManager.java]: yeah, Since this file contain `File.separator` in multiple places they will be fixed in another PR

Comment (Niranjan-K) [reply carbon-feature-plugin/src/main/java/org/wso2/maven/p2/utils/P2ApplicationLaunchManager.java]: @kasunsiyambalapitiya : Shall we fix this particular line in your code using @laki88 suggestion? For the other places where this is referred, can we create a separate Git issue.

Comment (kasunsiyambalapitiya) [reply carbon-feature-plugin/src/main/java/org/wso2/maven/p2/utils/P2ApplicationLaunchManager.java]: @Niranjan-K fixed with @laki88 suggestion and tested twice on both Linux and Windows

**Review by Niranjan-K — APPROVED** [review]
